default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hogehoge
  password: hogehoge
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: di-con_development

test:
  <<: *default
  database: di-con_test

production:
  <<: *default
  database: di-con_production
